spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_qq
          uri: http://www.qq.com
          predicates:
            - Query = url,qq
  application:
    name: gulimall-gateways
server:
  port: 88